---
- name: Create new host rsa pair keys
  openssh_keypair:
    path: "/etc/ssh/ssh_host_rsa_key"
    force: yes

- name: Create new host ed25519 keys
  openssh_keypair:
    path: "/etc/ssh/ssh_host_ed25519_key"
    force: yes

- name: Update sshd configuration safely, avoid locking yourself out
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes

- name: Install wanted packages
  apt:
    pkg:
    - tmux
    - atop
    - curl
    - tree
    - vim
    - mc
    - docker.io
    - sshguard
    - htpdate
    state: present

- name: Ensure docker is running
  service:
    name: docker
    state: started

- name: Start service htpdate if not started
  service:
    name: htpdate
    state: started

- name: Set timezone to Europe/Madrid and clock to UTC
  timezone:
    name: Europe/Madrid
    hwclock: UTC

- name: Ensure ufw is installed
  apt:
    name: ufw
    state: present

- name: ufw deny incoming
  ufw:
    direction: incoming
    proto: any
    policy: deny

- name: ufw allow outgoing
  ufw:
    direction: outgoing
    proto: any
    policy: allow

- name: ufw allow ssh
  ufw:
    rule: allow
    name: OpenSSH

- name: enable ufw service
  ufw:
    state: enabled

- name: "change hostname to {{ inventory_hostname }}"
  hostname:
    name: "{{ inventory_hostname }}"

- name: "add {{ inventory_hostname }} to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'
    state: present

- name: Ensure the en_US.UTF-8 locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Update .bashrc
  blockinfile:
    path: /root/.bashrc
    block: |
      export LC_ALL=en_US.UTF-8
      export LANG=en_US.UTF-8
      export LANGUAGE=en_US.UTF-8
      export NCURSES_NO_UTF8_ACS=1
       
- name: Install docker-compose
  vars:
   release: "1.26.2"
  get_url: 
    url : "https://github.com/docker/compose/releases/download/{{ release }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: reload ssh
  service:
    name: ssh 
    state: reloaded
