---
- name: "change hostname to {{ inventory_hostname }}"
  hostname:
    name: "{{ inventory_hostname }}"

- name: "add {{ inventory_hostname }} to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'
    state: present
