---
- name: Ensure the en_US.UTF-8 locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Update .bashrc
  blockinfile:
    path: /root/.bashrc
    block: |
      export LC_ALL=en_US.UTF-8
      export LANG=en_US.UTF-8
      export LANGUAGE=en_US.UTF-8
      export NCURSES_NO_UTF8_ACS=1
