---
- name: Install htpdate
  apt:
    pkg:
    - htpdate
    state: present

- name: Start service htpdate if not started
  service:
    name: htpdate
    state: started

- name: Set timezone to Europe/Madrid and clock to UTC
  timezone:
    name: Europe/Madrid
    hwclock: UTC
